### ISSUE TITLE
Static builder function for Sifter class

### ISSUE THREAD

**Issue by jdoyle65** [jdoyle65/SifterAPI#2]
Right now we're injecting a SifterCurl class into the constructor for Sifter. While this dependency injection is great for testing, it's kind of annoying for the user to have to instantiate an instance of SifterCurl themselves. Add a static build() function to Sifter that takes in the $apiKey and $apiSubdomain, instantiates a SifterCurl object itself, then construct a sifter class and return that.

**Comment by alefort** [comment]
As a user of your API, what would the calling of this Sifter API look like with the builder instead of the currently mandatory SifterCurl instance? Would the constructor simply take in the $apiKey and $apiSubdomain, or would I need to call some static method on the Sifter Class and pass that return into the Sifter Instance?

**Comment by jdoyle65** [comment]
I was thinking of something like `Sifter::build($apiKey, $apiSubdomain)` that would just return an instance of Sifter. The build method would take care of instantiating the SifterCurl that the Sifter constructor takes, making so the user doesn't have to care about the existence of SifterCurl.
