### ISSUE TITLE
Usefulness of Sifter::curl() function

### ISSUE THREAD

**Issue by alefort** [jdoyle65/SifterAPI#4]
In reviewing the Sifter class, I'm wondering why you chose a static function to wrap around a static instance variable (self::curl)? There must be a reason, and I'm not seeing it. All I see is the need for the extra () in the static call to curl.

Thoughts?

**Comment by jdoyle65** [comment]
The $curl static instance variable is wrapped by a static function call because it is a protected variable and cannot be accessed in a static context by classes other than the Sifter class. I didn't want to give other classes the ability to modify Sifter's $curl variable, only the ability to get and use it.

**Comment by jdoyle65** [comment]
Changed the static reference to SifterCurl in the Sifter class to an instanced reference.
